# Background


The struggle to define the serial verb construction (SVC) has led researchers to focus on finding commonalities which hold across a wide variety of languages.
A general consensus holds that a SVC consists of a string of two verbs acting as a single unit.
Most definitions additionally include the conditions of monoclausality [e.g. @dechaine1993, 799; @foleyolson1985, 18-32], a lack of overt marking between verbal elements within the construction [e.g. @foleyolson1985, 18; @collins1997, 462] and single eventhood [e.g. @durie1997; @aikhenvald2006, 3; @bisang2009]. Other potential restrictions include that the verbal elements must be able to be used as independent predicates elsewhere [e.g. @aikhenvald2006, 3; @haspelmath2016, 302-304], the construction is realised under a single intonation contour or within a single intonation unit [e.g. @givon1991; @bradshaw1993], and that at least one argument must be shared by the verbs within the construction [e.g. @baker1989; @sebba1987].

Some linguists do not consider the presence of any linking morphemes within the construction [@zwicky1990; @haspelmath2016], while others allow it, given that the marker does not indicate dependency of any sort [@aikhenvald2018, 3; @foleyolson1985; @foley2010]. 
Similarly, @crowley1987's 'ambient serialisation', where the state of affairs expressed by the first verbal element acts as the subject of the second verbal element, is accepted as a SVC by many [e.g. @aikhenvald2006], but rejected by others [e.g. @cleary-kemp2015; @haspelmath2016].

There is additionally a split in how results of a number of syntactic constituent tests are treated.
Aikhenvald [-@aikhenvald2018, 1] states that constituent verbal elements within an SVC cannot be extracted, separately negated or questioned, or used independently as the answer to a question.
Bisang [-@bisang2009, 796] explicitly allows for separate focusing of elements, but does not address other constituent tests; Sebba similarly allows for independent focusing and clefting of constituent elements [-@sebba1987, 65-71], while disallowing separate negation [-@sebba1987, 89]. Foley and Olson, on the other hand, allow for variation in the scope and marking of negation [-@foleyolson1985, 28; @foley2010, 102].

---

> ...while verbal-subject serial verbs can never be separated from the verbs they modify by an intonation break or a conjunction, ambient-subject serial verbs can, with no appreciable effet on grammaticality or basic meaning. (In that case, they can strictly speaking no longer be considered serialized.) [@bradshaw1993, 157]

---

We can link much of the theoretical debate over the definition of the serial verb construction back to one important issue: namely, if an SVC can constitute a legitimate grammatical construction or not. 
This point is anticipated by @himmelmann2022 when he argues that serial verb constructions are intonation unit-bounded, i.e. that a construction is only recognisable as an SVC when it is realised within a single intonation unit.
Only prosodically-robust, i.e. syntactic, constructions can undergo grammatical diagnostic tests such as substitution or extraction. 
These are the only constructions which are able to 'project'^[Note that I use 'project' here in an emergent/interactional sense, whereby the use of a given construction anticipates or foreshadows the upcoming use of a unit of language [cf. @auer2005a].] syntactic structures which persist over prosodic breaks and allow for incremental or reformulated realisations [cf. @hopperthompson2008].
All other constructions are prosodically dependent, whether they be IU-bounded or prosodic groupings (multi-IU constructions, such as lists).
The fact that a single intonation unit or contour is often cited as a criterion for SVCs suggests that these constructions, too, have not been fully grammaticalised.

There has been little comparative work investigating the prosodic realisation of serial verb constructions which could help shed light upon this issue. 
@givon1991's seminal study investigated the distribution of serial verbs across breath groups in four languages of Papua New Guinea, arguing that the distribution was similar to that of single lexemes.
He did not look at pauses occurring within serial verb constructions.
@unterladstetter2019 argues for the need to integrate prosodic analysis and discourse information management to understand the distribution of the kinds of multi-verbal constructions seen in Eastern Indonesia.
A theoretical accounting for different prosodic outputs of serialisation is put forward in @tylerkastner2022 from a generative perspective.
No wide-scale survey of the prosody of verb serialisation exists.

