# Discussion

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = TRUE, cache = TRUE) -->
<!-- ``` -->

The overall tendencies seen in the results of this study align with the hypotheses made in @givon1991 and @himmelmann2022. 
No language description mentioned that serial verb constructions could not be realised in a single intonation unit.^[The data here is obviously influenced by the original assumption made in the literature. I would hazard that information packaging also plays a large role here [cf. @himmelmann2013].] 
As such, we can conclude that all serial verb constructions *can* be realised in a single intonation unit.

My original question, however, was whether *all* serial verb constructions are realised in a single intonation unit. 
The hypothesis made by @himmelmann2022 was that serial verb constructions are IU-bounded constructions, i.e. that they *must* be realised in a single intonation unit as a prosody-dependent construction.
The data suggest that this is not the case in every language.
29 languages out of the 150 languages surveyed (~19.3%) had constructions which meet Himmelmann's definition of a prosodically-robust construction.
A further 4 languages (~2.7%) had prosodically-dependent constructions which are realised over multiple intonation units, i.e. prosodic groupings.
As such, we cannot make the generalisation that all SVCs must be realised within a single intonation unit.

## Areal Patterns

### Prosodically Robust (Grammatical) SVCs

The distribution of grammatical constructions has clear areal tendencies. The majority of languages with this type of construction are found in West Africa or Near Oceania, with a number also found in Central America and other parts of Africa. The reasons for which a construction was classified as grammatical differ between these areas.

Western African languages such as [Yoruba](\@(#yoruba)) or [Ewe](\@(#ewe)) pass constituency tests typical of grammatical constructions, such as focussing or extraction. 
Notably, two of the languages in Central America with grammatical SVCs are creoles (Saramaccan and Jamaican Creole English) which also allow for separate focussing of verbs through predicate clefting. 
Both of these languages have documented West African substrates with grammatical serial verb constructions  [@kramer2002; @patrick 2008].

In Near Oceania, prosodically-robust serial verb constructions typically shared a similar constructional template. 
This template consists of concatenated bare verb roots followed by a verb root which carries all relevant marking.
Some descriptions mention the possibility of pauses between roots (e.g. [Kalam](\@(#kalam)) and [Maybrat-Karon](\@(#maybrat-karon)), which help support the analysis of these constructions as prosodically robust.

### Prosodically Grouped SVCs

All examples of prosodically-grouped serial verb constructions come from Near Oceania. It is unclear whether this reflects a true areal pattern or simply a descriptive bias.
It is also unclear if this distribution could be tied to areal intonation patterns, largely due to a lack of documentation and comparative work [@himmelmannkaufmann2020].^[A number of language-specific descriptions posit H% boundary tones, which could form an areal pattern, e.g. in Matukar Panau [@mansfieldbarth2021], Daakaka [@vonprince2012] and Kéo [@baird2002].]

### Single Word SVCs

A potentially important areal generalisation the tendency for SVCs to be realised as single words in the Americas.
In many cases, the word features both left- and right-edge phenomena, thus making these constructions good candidates to be prosodically-robust. However, it is yet unclear to what extent these are treated as words in discourse with regards to e.g. repair processes.
If repair processes result most often in the restart of the whole word, then these SVCs would also be classified as IU-bounded construction type despite a distinct constructional profile.

## Structural Patterns

### Prosodically Grouped SVCs

The languages in which prosodically grouped SVCs are found also make use of IU-bounded serial verb constructions.
The realisation of the construction within a single IU or across multiple IUs appears to be correlated with whether the serial verb construction is nuclear or core-level [cf. @foleyolson1985].
No nuclear serial verb constructions were used in the explication of multi-IU constructions, suggesting that this is related to a higher-level syntactic juncture.

### Juxtaposition as Source Construction

Data from a number of languages show links between clausal juxtaposition and serial verb constructions. This link may explain the use of SVCs as a discourse-summarising device, particularly the 'narrative' SVC type [@pawley1987; @vanstadenreesink2004]. Further investigation into the potential correlation of formal marking strategies or information packaging tendencies with this type would help to ascertain whether this is a robust grammaticalisation pathway.
